CAREERS_DATABASE = [
    # Technology & Software
    {
        "id": "software_engineer",
        "title": "Software Engineer",
        "description": "Design, develop, and maintain software applications and systems. Work with programming languages, frameworks, and tools to build solutions for various industries.",
        "industry": "Technology",
        "required_skills": ["programming", "problem_solving", "algorithms", "software_design", "debugging"],
        "preferred_skills": ["cloud_computing", "databases", "api_development", "version_control"],
        "interests": ["technology", "problem_solving", "innovation", "coding"],
        "education_level": "bachelors",
        "experience_range": {"min": 0, "max": 20},
        "salary_range": {"min": 70000, "max": 180000},
        "salary_category": "high",
        "growth_outlook": "Excellent",
        "work_styles": ["remote", "hybrid", "onsite"],
        "career_path": ["Junior Developer", "Mid-Level Developer", "Senior Developer", "Tech Lead", "Principal Engineer", "CTO"]
    },
    {
        "id": "data_scientist",
        "title": "Data Scientist",
        "description": "Analyze complex data sets to find patterns and insights. Use statistical methods and machine learning to solve business problems and drive decision-making.",
        "industry": "Technology",
        "required_skills": ["data_analysis", "statistics", "python", "machine_learning", "problem_solving"],
        "preferred_skills": ["deep_learning", "big_data", "visualization", "sql"],
        "interests": ["data", "research", "problem_solving", "mathematics"],
        "education_level": "masters",
        "experience_range": {"min": 0, "max": 15},
        "salary_range": {"min": 85000, "max": 200000},
        "salary_category": "high",
        "growth_outlook": "Excellent",
        "work_styles": ["remote", "hybrid"],
        "career_path": ["Junior Data Scientist", "Data Scientist", "Senior Data Scientist", "Lead Data Scientist", "Director of Data Science", "Chief Data Officer"]
    },
    {
        "id": "web_developer",
        "title": "Web Developer",
        "description": "Create and maintain websites and web applications. Work with HTML, CSS, JavaScript, and various frameworks to build user-friendly web experiences.",
        "industry": "Technology",
        "required_skills": ["html_css", "javascript", "web_design", "responsive_design"],
        "preferred_skills": ["react", "nodejs", "databases", "api_development"],
        "interests": ["design", "technology", "creativity", "coding"],
        "education_level": "bachelors",
        "experience_range": {"min": 0, "max": 15},
        "salary_range": {"min": 55000, "max": 140000},
        "salary_category": "high",
        "growth_outlook": "Very Good",
        "work_styles": ["remote", "hybrid", "onsite"],
        "career_path": ["Junior Web Developer", "Web Developer", "Senior Web Developer", "Full Stack Developer", "Tech Lead", "Engineering Manager"]
    },
    {
        "id": "cybersecurity_analyst",
        "title": "Cybersecurity Analyst",
        "description": "Protect organizations from cyber threats by monitoring systems, analyzing security risks, and implementing security measures.",
        "industry": "Technology",
        "required_skills": ["network_security", "risk_assessment", "security_tools", "problem_solving"],
        "preferred_skills": ["ethical_hacking", "cloud_security", "incident_response", "programming"],
        "interests": ["security", "technology", "problem_solving", "investigation"],
        "education_level": "bachelors",
        "experience_range": {"min": 1, "max": 20},
        "salary_range": {"min": 75000, "max": 160000},
        "salary_category": "high",
        "growth_outlook": "Excellent",
        "work_styles": ["hybrid", "onsite"],
        "career_path": ["Security Analyst", "Senior Security Analyst", "Security Engineer", "Security Architect", "CISO"]
    },
    {
        "id": "devops_engineer",
        "title": "DevOps Engineer",
        "description": "Bridge development and operations by automating infrastructure, managing deployments, and ensuring system reliability.",
        "industry": "Technology",
        "required_skills": ["linux", "cloud_computing", "automation", "ci_cd", "scripting"],
        "preferred_skills": ["kubernetes", "docker", "terraform", "monitoring"],
        "interests": ["technology", "automation", "problem_solving", "systems"],
        "education_level": "bachelors",
        "experience_range": {"min": 2, "max": 15},
        "salary_range": {"min": 90000, "max": 180000},
        "salary_category": "high",
        "growth_outlook": "Excellent",
        "work_styles": ["remote", "hybrid"],
        "career_path": ["Junior DevOps Engineer", "DevOps Engineer", "Senior DevOps Engineer", "Platform Engineer", "Site Reliability Engineer", "VP of Infrastructure"]
    },
    {
        "id": "mobile_developer",
        "title": "Mobile App Developer",
        "description": "Design and build applications for mobile devices. Develop for iOS, Android, or cross-platform using various frameworks and tools.",
        "industry": "Technology",
        "required_skills": ["mobile_development", "programming", "ui_design", "api_integration"],
        "preferred_skills": ["swift", "kotlin", "react_native", "flutter"],
        "interests": ["technology", "design", "mobile", "innovation"],
        "education_level": "bachelors",
        "experience_range": {"min": 0, "max": 15},
        "salary_range": {"min": 70000, "max": 160000},
        "salary_category": "high",
        "growth_outlook": "Very Good",
        "work_styles": ["remote", "hybrid"],
        "career_path": ["Junior Mobile Developer", "Mobile Developer", "Senior Mobile Developer", "Lead Mobile Developer", "Mobile Architect"]
    },
    {
        "id": "ai_engineer",
        "title": "AI/ML Engineer",
        "description": "Build and deploy artificial intelligence and machine learning models. Develop intelligent systems that can learn and make decisions.",
        "industry": "Technology",
        "required_skills": ["machine_learning", "python", "deep_learning", "mathematics", "programming"],
        "preferred_skills": ["tensorflow", "pytorch", "nlp", "computer_vision"],
        "interests": ["artificial_intelligence", "research", "innovation", "mathematics"],
        "education_level": "masters",
        "experience_range": {"min": 1, "max": 15},
        "salary_range": {"min": 100000, "max": 250000},
        "salary_category": "high",
        "growth_outlook": "Excellent",
        "work_styles": ["remote", "hybrid"],
        "career_path": ["ML Engineer", "Senior ML Engineer", "Staff ML Engineer", "Principal ML Engineer", "Head of AI"]
    },
    {
        "id": "cloud_architect",
        "title": "Cloud Architect",
        "description": "Design and oversee cloud computing strategies. Plan cloud infrastructure and ensure scalability, security, and efficiency.",
        "industry": "Technology",
        "required_skills": ["cloud_computing", "architecture_design", "networking", "security", "problem_solving"],
        "preferred_skills": ["aws", "azure", "gcp", "kubernetes"],
        "interests": ["technology", "architecture", "innovation", "systems"],
        "education_level": "bachelors",
        "experience_range": {"min": 5, "max": 20},
        "salary_range": {"min": 130000, "max": 220000},
        "salary_category": "high",
        "growth_outlook": "Excellent",
        "work_styles": ["remote", "hybrid"],
        "career_path": ["Cloud Engineer", "Senior Cloud Engineer", "Cloud Architect", "Principal Architect", "VP of Cloud Infrastructure"]
    },
    {
        "id": "database_administrator",
        "title": "Database Administrator",
        "description": "Manage and maintain database systems. Ensure data integrity, security, and optimal performance of database infrastructure.",
        "industry": "Technology",
        "required_skills": ["databases", "sql", "data_management", "backup_recovery", "performance_tuning"],
        "preferred_skills": ["cloud_databases", "nosql", "scripting", "security"],
        "interests": ["data", "organization", "technology", "problem_solving"],
        "education_level": "bachelors",
        "experience_range": {"min": 2, "max": 20},
        "salary_range": {"min": 70000, "max": 140000},
        "salary_category": "high",
        "growth_outlook": "Good",
        "work_styles": ["hybrid", "onsite"],
        "career_path": ["Junior DBA", "Database Administrator", "Senior DBA", "Lead DBA", "Database Architect", "Director of Data Management"]
    },
    {
        "id": "qa_engineer",
        "title": "QA Engineer",
        "description": "Ensure software quality through testing and quality assurance processes. Develop test plans, automate testing, and identify bugs.",
        "industry": "Technology",
        "required_skills": ["testing", "automation", "attention_to_detail", "problem_solving", "documentation"],
        "preferred_skills": ["selenium", "programming", "ci_cd", "performance_testing"],
        "interests": ["quality", "technology", "detail_oriented", "problem_solving"],
        "education_level": "bachelors",
        "experience_range": {"min": 0, "max": 15},
        "salary_range": {"min": 60000, "max": 130000},
        "salary_category": "medium",
        "growth_outlook": "Good",
        "work_styles": ["remote", "hybrid"],
        "career_path": ["QA Analyst", "QA Engineer", "Senior QA Engineer", "QA Lead", "QA Manager", "Director of Quality"]
    },
    
    # Healthcare
    {
        "id": "physician",
        "title": "Physician",
        "description": "Diagnose and treat illnesses and injuries. Provide preventive care and health education to patients.",
        "industry": "Healthcare",
        "required_skills": ["medical_knowledge", "patient_care", "diagnosis", "communication", "decision_making"],
        "preferred_skills": ["research", "leadership", "technology", "empathy"],
        "interests": ["healthcare", "helping_others", "science", "medicine"],
        "education_level": "doctorate",
        "experience_range": {"min": 3, "max": 40},
        "salary_range": {"min": 180000, "max": 400000},
        "salary_category": "high",
        "growth_outlook": "Good",
        "work_styles": ["onsite"],
        "career_path": ["Resident", "Attending Physician", "Senior Physician", "Department Head", "Chief Medical Officer"]
    },
    {
        "id": "registered_nurse",
        "title": "Registered Nurse",
        "description": "Provide and coordinate patient care. Educate patients about health conditions and provide emotional support.",
        "industry": "Healthcare",
        "required_skills": ["patient_care", "medical_knowledge", "communication", "empathy", "critical_thinking"],
        "preferred_skills": ["leadership", "technology", "stress_management", "teamwork"],
        "interests": ["healthcare", "helping_others", "caregiving", "medicine"],
        "education_level": "bachelors",
        "experience_range": {"min": 0, "max": 30},
        "salary_range": {"min": 60000, "max": 120000},
        "salary_category": "medium",
        "growth_outlook": "Very Good",
        "work_styles": ["onsite"],
        "career_path": ["Staff Nurse", "Senior Nurse", "Charge Nurse", "Nurse Manager", "Director of Nursing", "Chief Nursing Officer"]
    },
    {
        "id": "pharmacist",
        "title": "Pharmacist",
        "description": "Dispense medications and provide expertise in safe drug use. Advise patients and healthcare providers about medications.",
        "industry": "Healthcare",
        "required_skills": ["pharmaceutical_knowledge", "attention_to_detail", "patient_care", "communication", "chemistry"],
        "preferred_skills": ["research", "management", "technology", "counseling"],
        "interests": ["healthcare", "science", "helping_others", "medicine"],
        "education_level": "doctorate",
        "experience_range": {"min": 0, "max": 30},
        "salary_range": {"min": 100000, "max": 160000},
        "salary_category": "high",
        "growth_outlook": "Good",
        "work_styles": ["onsite"],
        "career_path": ["Staff Pharmacist", "Clinical Pharmacist", "Pharmacy Manager", "Regional Pharmacy Director", "VP of Pharmacy Operations"]
    },
    {
        "id": "physical_therapist",
        "title": "Physical Therapist",
        "description": "Help patients recover from injuries and improve physical mobility. Develop treatment plans and guide rehabilitation exercises.",
        "industry": "Healthcare",
        "required_skills": ["anatomy_knowledge", "patient_care", "treatment_planning", "communication", "physical_fitness"],
        "preferred_skills": ["manual_therapy", "technology", "sports_medicine", "empathy"],
        "interests": ["healthcare", "fitness", "helping_others", "rehabilitation"],
        "education_level": "doctorate",
        "experience_range": {"min": 0, "max": 25},
        "salary_range": {"min": 70000, "max": 120000},
        "salary_category": "medium",
        "growth_outlook": "Very Good",
        "work_styles": ["onsite", "hybrid"],
        "career_path": ["Staff PT", "Senior PT", "Clinical Specialist", "Clinic Director", "Regional Director"]
    },
    {
        "id": "medical_researcher",
        "title": "Medical Researcher",
        "description": "Conduct research to improve overall human health. Investigate ways to prevent and treat diseases.",
        "industry": "Healthcare",
        "required_skills": ["research", "data_analysis", "scientific_method", "writing", "critical_thinking"],
        "preferred_skills": ["laboratory_skills", "statistics", "grant_writing", "collaboration"],
        "interests": ["research", "science", "healthcare", "discovery"],
        "education_level": "doctorate",
        "experience_range": {"min": 0, "max": 30},
        "salary_range": {"min": 60000, "max": 150000},
        "salary_category": "high",
        "growth_outlook": "Good",
        "work_styles": ["onsite", "hybrid"],
        "career_path": ["Research Associate", "Scientist", "Senior Scientist", "Principal Investigator", "Research Director"]
    },
    {
        "id": "healthcare_administrator",
        "title": "Healthcare Administrator",
        "description": "Plan, direct, and coordinate medical and health services. Manage healthcare facilities, departments, or practices.",
        "industry": "Healthcare",
        "required_skills": ["management", "healthcare_knowledge", "budgeting", "communication", "leadership"],
        "preferred_skills": ["strategic_planning", "regulatory_compliance", "technology", "negotiation"],
        "interests": ["healthcare", "management", "organization", "leadership"],
        "education_level": "masters",
        "experience_range": {"min": 3, "max": 25},
        "salary_range": {"min": 80000, "max": 180000},
        "salary_category": "high",
        "growth_outlook": "Good",
        "work_styles": ["onsite", "hybrid"],
        "career_path": ["Department Manager", "Administrator", "Director", "VP of Operations", "CEO"]
    },
    
    # Business & Finance
    {
        "id": "financial_analyst",
        "title": "Financial Analyst",
        "description": "Analyze financial data and trends. Provide recommendations for business decisions and investment strategies.",
        "industry": "Finance",
        "required_skills": ["financial_analysis", "excel", "data_analysis", "reporting", "critical_thinking"],
        "preferred_skills": ["financial_modeling", "sql", "presentation", "industry_knowledge"],
        "interests": ["finance", "business", "analysis", "economics"],
        "education_level": "bachelors",
        "experience_range": {"min": 0, "max": 20},
        "salary_range": {"min": 60000, "max": 150000},
        "salary_category": "high",
        "growth_outlook": "Good",
        "work_styles": ["hybrid", "onsite"],
        "career_path": ["Junior Analyst", "Financial Analyst", "Senior Analyst", "Finance Manager", "Director of Finance", "CFO"]
    },
    {
        "id": "investment_banker",
        "title": "Investment Banker",
        "description": "Help clients raise capital and provide advisory services for mergers, acquisitions, and other financial transactions.",
        "industry": "Finance",
        "required_skills": ["financial_analysis", "valuation", "negotiation", "presentation", "networking"],
        "preferred_skills": ["modeling", "industry_expertise", "deal_making", "leadership"],
        "interests": ["finance", "business", "deal_making", "high_pressure"],
        "education_level": "masters",
        "experience_range": {"min": 0, "max": 25},
        "salary_range": {"min": 100000, "max": 400000},
        "salary_category": "high",
        "growth_outlook": "Good",
        "work_styles": ["onsite"],
        "career_path": ["Analyst", "Associate", "VP", "Director", "Managing Director", "Partner"]
    },
    {
        "id": "accountant",
        "title": "Accountant",
        "description": "Prepare and examine financial records. Ensure accuracy and compliance with laws and regulations.",
        "industry": "Finance",
        "required_skills": ["accounting", "attention_to_detail", "excel", "tax_knowledge", "financial_reporting"],
        "preferred_skills": ["auditing", "erp_systems", "analytical_skills", "communication"],
        "interests": ["finance", "organization", "detail_oriented", "business"],
        "education_level": "bachelors",
        "experience_range": {"min": 0, "max": 30},
        "salary_range": {"min": 50000, "max": 120000},
        "salary_category": "medium",
        "growth_outlook": "Good",
        "work_styles": ["hybrid", "remote", "onsite"],
        "career_path": ["Staff Accountant", "Senior Accountant", "Accounting Manager", "Controller", "CFO"]
    },
    {
        "id": "management_consultant",
        "title": "Management Consultant",
        "description": "Help organizations improve performance through analysis of existing problems and development of improvement plans.",
        "industry": "Consulting",
        "required_skills": ["problem_solving", "analysis", "presentation", "communication", "strategic_thinking"],
        "preferred_skills": ["project_management", "industry_expertise", "data_analysis", "leadership"],
        "interests": ["business", "problem_solving", "strategy", "variety"],
        "education_level": "masters",
        "experience_range": {"min": 0, "max": 20},
        "salary_range": {"min": 80000, "max": 250000},
        "salary_category": "high",
        "growth_outlook": "Good",
        "work_styles": ["hybrid", "onsite"],
        "career_path": ["Analyst", "Consultant", "Senior Consultant", "Manager", "Principal", "Partner"]
    },
    {
        "id": "product_manager",
        "title": "Product Manager",
        "description": "Guide the success of a product and lead cross-functional teams. Define product vision, strategy, and roadmap.",
        "industry": "Technology",
        "required_skills": ["product_strategy", "communication", "analysis", "leadership", "project_management"],
        "preferred_skills": ["technical_knowledge", "user_research", "data_analysis", "agile"],
        "interests": ["technology", "business", "innovation", "leadership"],
        "education_level": "bachelors",
        "experience_range": {"min": 2, "max": 20},
        "salary_range": {"min": 90000, "max": 200000},
        "salary_category": "high",
        "growth_outlook": "Excellent",
        "work_styles": ["hybrid", "remote"],
        "career_path": ["Associate PM", "Product Manager", "Senior PM", "Director of Product", "VP of Product", "Chief Product Officer"]
    },
    {
        "id": "marketing_manager",
        "title": "Marketing Manager",
        "description": "Plan and execute marketing strategies to promote products or services. Oversee campaigns, brand management, and market research.",
        "industry": "Marketing",
        "required_skills": ["marketing_strategy", "communication", "creativity", "analytics", "project_management"],
        "preferred_skills": ["digital_marketing", "content_strategy", "brand_management", "leadership"],
        "interests": ["marketing", "creativity", "business", "communication"],
        "education_level": "bachelors",
        "experience_range": {"min": 2, "max": 20},
        "salary_range": {"min": 65000, "max": 150000},
        "salary_category": "high",
        "growth_outlook": "Good",
        "work_styles": ["hybrid", "remote", "onsite"],
        "career_path": ["Marketing Coordinator", "Marketing Specialist", "Marketing Manager", "Senior Marketing Manager", "Director of Marketing", "CMO"]
    },
    {
        "id": "hr_manager",
        "title": "Human Resources Manager",
        "description": "Plan and coordinate HR activities. Oversee recruiting, employee relations, compensation, and organizational development.",
        "industry": "Human Resources",
        "required_skills": ["communication", "conflict_resolution", "employment_law", "recruiting", "leadership"],
        "preferred_skills": ["hris_systems", "training_development", "analytics", "strategic_planning"],
        "interests": ["people", "organization", "helping_others", "business"],
        "education_level": "bachelors",
        "experience_range": {"min": 3, "max": 25},
        "salary_range": {"min": 70000, "max": 140000},
        "salary_category": "high",
        "growth_outlook": "Good",
        "work_styles": ["hybrid", "onsite"],
        "career_path": ["HR Coordinator", "HR Generalist", "HR Manager", "HR Director", "VP of HR", "CHRO"]
    },
    {
        "id": "business_analyst",
        "title": "Business Analyst",
        "description": "Bridge IT and business by analyzing processes, determining requirements, and delivering data-driven recommendations.",
        "industry": "Technology",
        "required_skills": ["analysis", "requirements_gathering", "documentation", "communication", "problem_solving"],
        "preferred_skills": ["sql", "data_visualization", "process_modeling", "agile"],
        "interests": ["business", "technology", "problem_solving", "organization"],
        "education_level": "bachelors",
        "experience_range": {"min": 0, "max": 15},
        "salary_range": {"min": 60000, "max": 120000},
        "salary_category": "medium",
        "growth_outlook": "Good",
        "work_styles": ["hybrid", "remote"],
        "career_path": ["Junior BA", "Business Analyst", "Senior BA", "Lead BA", "Business Architect", "Director of Business Analysis"]
    },
    {
        "id": "project_manager",
        "title": "Project Manager",
        "description": "Plan, execute, and close projects. Lead teams, manage budgets, and ensure projects are delivered on time and within scope.",
        "industry": "Multiple",
        "required_skills": ["project_management", "communication", "leadership", "problem_solving", "organization"],
        "preferred_skills": ["agile", "risk_management", "budgeting", "stakeholder_management"],
        "interests": ["organization", "leadership", "problem_solving", "teamwork"],
        "education_level": "bachelors",
        "experience_range": {"min": 2, "max": 25},
        "salary_range": {"min": 70000, "max": 150000},
        "salary_category": "high",
        "growth_outlook": "Good",
        "work_styles": ["hybrid", "onsite"],
        "career_path": ["Project Coordinator", "Project Manager", "Senior PM", "Program Manager", "Director of PMO", "VP of Operations"]
    },
    
    # Creative & Design
    {
        "id": "ux_designer",
        "title": "UX Designer",
        "description": "Design user experiences for digital products. Conduct research, create wireframes, and ensure products are intuitive and user-friendly.",
        "industry": "Design",
        "required_skills": ["user_research", "wireframing", "prototyping", "usability_testing", "design_thinking"],
        "preferred_skills": ["figma", "interaction_design", "visual_design", "html_css"],
        "interests": ["design", "technology", "psychology", "problem_solving"],
        "education_level": "bachelors",
        "experience_range": {"min": 0, "max": 15},
        "salary_range": {"min": 70000, "max": 150000},
        "salary_category": "high",
        "growth_outlook": "Excellent",
        "work_styles": ["remote", "hybrid"],
        "career_path": ["Junior UX Designer", "UX Designer", "Senior UX Designer", "Lead UX Designer", "UX Director", "VP of Design"]
    },
    {
        "id": "graphic_designer",
        "title": "Graphic Designer",
        "description": "Create visual concepts to communicate ideas. Design layouts, graphics, and visual elements for various media.",
        "industry": "Design",
        "required_skills": ["visual_design", "creativity", "adobe_creative_suite", "typography", "color_theory"],
        "preferred_skills": ["illustration", "branding", "motion_graphics", "web_design"],
        "interests": ["design", "creativity", "art", "visual_communication"],
        "education_level": "bachelors",
        "experience_range": {"min": 0, "max": 20},
        "salary_range": {"min": 45000, "max": 90000},
        "salary_category": "medium",
        "growth_outlook": "Good",
        "work_styles": ["remote", "hybrid", "onsite"],
        "career_path": ["Junior Designer", "Graphic Designer", "Senior Designer", "Art Director", "Creative Director"]
    },
    {
        "id": "content_writer",
        "title": "Content Writer",
        "description": "Create written content for various platforms. Write articles, blog posts, marketing copy, and other content forms.",
        "industry": "Media",
        "required_skills": ["writing", "research", "seo", "creativity", "editing"],
        "preferred_skills": ["content_strategy", "social_media", "marketing", "storytelling"],
        "interests": ["writing", "creativity", "communication", "research"],
        "education_level": "bachelors",
        "experience_range": {"min": 0, "max": 20},
        "salary_range": {"min": 40000, "max": 90000},
        "salary_category": "medium",
        "growth_outlook": "Good",
        "work_styles": ["remote", "hybrid"],
        "career_path": ["Junior Writer", "Content Writer", "Senior Writer", "Content Manager", "Content Director", "VP of Content"]
    },
    {
        "id": "video_producer",
        "title": "Video Producer",
        "description": "Plan, shoot, and edit video content. Manage video production from concept to final delivery.",
        "industry": "Media",
        "required_skills": ["video_editing", "storytelling", "camera_operation", "creative_direction", "project_management"],
        "preferred_skills": ["motion_graphics", "sound_design", "color_grading", "live_streaming"],
        "interests": ["video", "creativity", "storytelling", "technology"],
        "education_level": "bachelors",
        "experience_range": {"min": 0, "max": 20},
        "salary_range": {"min": 45000, "max": 120000},
        "salary_category": "medium",
        "growth_outlook": "Good",
        "work_styles": ["hybrid", "onsite", "remote"],
        "career_path": ["Production Assistant", "Video Editor", "Producer", "Senior Producer", "Executive Producer", "Head of Production"]
    },
    {
        "id": "animator",
        "title": "Animator",
        "description": "Create animations for films, games, and digital media. Bring characters and stories to life through motion.",
        "industry": "Entertainment",
        "required_skills": ["animation", "creativity", "storytelling", "timing", "attention_to_detail"],
        "preferred_skills": ["3d_modeling", "character_design", "motion_capture", "vfx"],
        "interests": ["animation", "art", "storytelling", "entertainment"],
        "education_level": "bachelors",
        "experience_range": {"min": 0, "max": 20},
        "salary_range": {"min": 50000, "max": 120000},
        "salary_category": "medium",
        "growth_outlook": "Good",
        "work_styles": ["remote", "hybrid", "onsite"],
        "career_path": ["Junior Animator", "Animator", "Senior Animator", "Lead Animator", "Animation Director"]
    },
    {
        "id": "architect",
        "title": "Architect",
        "description": "Design buildings and structures. Create plans that are functional, safe, and aesthetically pleasing.",
        "industry": "Architecture",
        "required_skills": ["architectural_design", "cad_software", "creativity", "technical_drawing", "building_codes"],
        "preferred_skills": ["3d_modeling", "sustainability", "project_management", "bim"],
        "interests": ["design", "architecture", "creativity", "construction"],
        "education_level": "masters",
        "experience_range": {"min": 0, "max": 30},
        "salary_range": {"min": 60000, "max": 150000},
        "salary_category": "high",
        "growth_outlook": "Good",
        "work_styles": ["hybrid", "onsite"],
        "career_path": ["Intern Architect", "Architect", "Senior Architect", "Project Architect", "Principal Architect", "Firm Partner"]
    },
    
    # Education
    {
        "id": "teacher",
        "title": "Teacher",
        "description": "Educate students in various subjects. Create lesson plans, assess student progress, and foster learning environments.",
        "industry": "Education",
        "required_skills": ["teaching", "communication", "patience", "organization", "subject_knowledge"],
        "preferred_skills": ["curriculum_development", "technology", "classroom_management", "mentoring"],
        "interests": ["education", "helping_others", "learning", "youth"],
        "education_level": "bachelors",
        "experience_range": {"min": 0, "max": 35},
        "salary_range": {"min": 40000, "max": 80000},
        "salary_category": "medium",
        "growth_outlook": "Good",
        "work_styles": ["onsite"],
        "career_path": ["Teacher", "Senior Teacher", "Department Head", "Assistant Principal", "Principal", "Superintendent"]
    },
    {
        "id": "professor",
        "title": "University Professor",
        "description": "Teach at higher education institutions. Conduct research, publish papers, and mentor graduate students.",
        "industry": "Education",
        "required_skills": ["research", "teaching", "writing", "subject_expertise", "critical_thinking"],
        "preferred_skills": ["grant_writing", "mentoring", "public_speaking", "collaboration"],
        "interests": ["education", "research", "academia", "learning"],
        "education_level": "doctorate",
        "experience_range": {"min": 0, "max": 40},
        "salary_range": {"min": 60000, "max": 180000},
        "salary_category": "high",
        "growth_outlook": "Fair",
        "work_styles": ["hybrid", "onsite"],
        "career_path": ["Assistant Professor", "Associate Professor", "Full Professor", "Department Chair", "Dean", "Provost"]
    },
    {
        "id": "instructional_designer",
        "title": "Instructional Designer",
        "description": "Design and develop educational programs and materials. Create effective learning experiences for various audiences.",
        "industry": "Education",
        "required_skills": ["curriculum_design", "e_learning", "writing", "project_management", "creativity"],
        "preferred_skills": ["lms_platforms", "video_production", "assessment_design", "accessibility"],
        "interests": ["education", "technology", "design", "learning"],
        "education_level": "masters",
        "experience_range": {"min": 0, "max": 20},
        "salary_range": {"min": 55000, "max": 100000},
        "salary_category": "medium",
        "growth_outlook": "Very Good",
        "work_styles": ["remote", "hybrid"],
        "career_path": ["Instructional Designer", "Senior ID", "Lead ID", "Learning Manager", "Director of Learning"]
    },
    {
        "id": "education_consultant",
        "title": "Education Consultant",
        "description": "Advise schools and educational organizations. Help improve educational practices, curriculum, and outcomes.",
        "industry": "Education",
        "required_skills": ["educational_expertise", "consulting", "communication", "analysis", "strategic_planning"],
        "preferred_skills": ["data_analysis", "change_management", "training", "research"],
        "interests": ["education", "consulting", "improvement", "policy"],
        "education_level": "masters",
        "experience_range": {"min": 5, "max": 30},
        "salary_range": {"min": 60000, "max": 130000},
        "salary_category": "high",
        "growth_outlook": "Good",
        "work_styles": ["hybrid", "remote"],
        "career_path": ["Education Consultant", "Senior Consultant", "Principal Consultant", "Partner"]
    },
    
    # Legal
    {
        "id": "lawyer",
        "title": "Lawyer/Attorney",
        "description": "Represent clients in legal proceedings. Advise on legal rights, obligations, and strategies.",
        "industry": "Legal",
        "required_skills": ["legal_research", "writing", "negotiation", "communication", "critical_thinking"],
        "preferred_skills": ["litigation", "contract_drafting", "public_speaking", "client_management"],
        "interests": ["law", "justice", "advocacy", "research"],
        "education_level": "doctorate",
        "experience_range": {"min": 0, "max": 40},
        "salary_range": {"min": 70000, "max": 300000},
        "salary_category": "high",
        "growth_outlook": "Good",
        "work_styles": ["onsite", "hybrid"],
        "career_path": ["Associate", "Senior Associate", "Counsel", "Partner", "Managing Partner"]
    },
    {
        "id": "paralegal",
        "title": "Paralegal",
        "description": "Support lawyers by conducting research, preparing documents, and managing case files.",
        "industry": "Legal",
        "required_skills": ["legal_research", "writing", "organization", "attention_to_detail", "communication"],
        "preferred_skills": ["legal_software", "document_management", "interviewing", "filing"],
        "interests": ["law", "organization", "research", "detail_oriented"],
        "education_level": "associates",
        "experience_range": {"min": 0, "max": 25},
        "salary_range": {"min": 40000, "max": 75000},
        "salary_category": "medium",
        "growth_outlook": "Good",
        "work_styles": ["onsite", "hybrid"],
        "career_path": ["Paralegal", "Senior Paralegal", "Paralegal Manager", "Legal Operations Manager"]
    },
    {
        "id": "compliance_officer",
        "title": "Compliance Officer",
        "description": "Ensure organizations comply with laws and regulations. Develop policies and conduct compliance audits.",
        "industry": "Legal",
        "required_skills": ["regulatory_knowledge", "analysis", "communication", "attention_to_detail", "risk_assessment"],
        "preferred_skills": ["auditing", "policy_development", "training", "investigation"],
        "interests": ["law", "ethics", "organization", "risk_management"],
        "education_level": "bachelors",
        "experience_range": {"min": 2, "max": 25},
        "salary_range": {"min": 60000, "max": 140000},
        "salary_category": "high",
        "growth_outlook": "Good",
        "work_styles": ["hybrid", "onsite"],
        "career_path": ["Compliance Analyst", "Compliance Officer", "Senior Compliance Officer", "Compliance Director", "Chief Compliance Officer"]
    },
    
    # Science & Research
    {
        "id": "research_scientist",
        "title": "Research Scientist",
        "description": "Conduct scientific research to advance knowledge. Design experiments, analyze data, and publish findings.",
        "industry": "Science",
        "required_skills": ["research", "data_analysis", "scientific_method", "writing", "critical_thinking"],
        "preferred_skills": ["laboratory_skills", "statistics", "programming", "grant_writing"],
        "interests": ["science", "research", "discovery", "learning"],
        "education_level": "doctorate",
        "experience_range": {"min": 0, "max": 30},
        "salary_range": {"min": 60000, "max": 150000},
        "salary_category": "high",
        "growth_outlook": "Good",
        "work_styles": ["onsite", "hybrid"],
        "career_path": ["Postdoc", "Research Scientist", "Senior Scientist", "Principal Scientist", "Research Director"]
    },
    {
        "id": "environmental_scientist",
        "title": "Environmental Scientist",
        "description": "Study environmental issues and develop solutions. Conduct research on pollution, climate change, and conservation.",
        "industry": "Environmental",
        "required_skills": ["environmental_science", "data_analysis", "research", "writing", "fieldwork"],
        "preferred_skills": ["gis", "policy_knowledge", "statistics", "project_management"],
        "interests": ["environment", "science", "sustainability", "nature"],
        "education_level": "masters",
        "experience_range": {"min": 0, "max": 25},
        "salary_range": {"min": 55000, "max": 110000},
        "salary_category": "medium",
        "growth_outlook": "Good",
        "work_styles": ["hybrid", "onsite"],
        "career_path": ["Environmental Scientist", "Senior Scientist", "Project Manager", "Environmental Director"]
    },
    {
        "id": "biotech_researcher",
        "title": "Biotechnology Researcher",
        "description": "Apply biological systems to develop new products and technologies. Work on pharmaceuticals, agriculture, or industrial applications.",
        "industry": "Biotechnology",
        "required_skills": ["molecular_biology", "laboratory_skills", "research", "data_analysis", "problem_solving"],
        "preferred_skills": ["bioinformatics", "programming", "cell_culture", "protein_engineering"],
        "interests": ["science", "biotechnology", "research", "innovation"],
        "education_level": "doctorate",
        "experience_range": {"min": 0, "max": 25},
        "salary_range": {"min": 70000, "max": 160000},
        "salary_category": "high",
        "growth_outlook": "Excellent",
        "work_styles": ["onsite"],
        "career_path": ["Research Associate", "Scientist", "Senior Scientist", "Principal Scientist", "Research Director", "CSO"]
    },
    
    # Trades & Skilled Labor
    {
        "id": "electrician",
        "title": "Electrician",
        "description": "Install, maintain, and repair electrical systems. Work on wiring, lighting, and electrical equipment.",
        "industry": "Trades",
        "required_skills": ["electrical_systems", "troubleshooting", "safety", "blueprint_reading", "manual_dexterity"],
        "preferred_skills": ["plc_programming", "renewable_energy", "project_management", "customer_service"],
        "interests": ["trades", "hands_on_work", "problem_solving", "construction"],
        "education_level": "vocational",
        "experience_range": {"min": 0, "max": 30},
        "salary_range": {"min": 45000, "max": 100000},
        "salary_category": "medium",
        "growth_outlook": "Very Good",
        "work_styles": ["onsite"],
        "career_path": ["Apprentice", "Journeyman", "Master Electrician", "Electrical Contractor", "Business Owner"]
    },
    {
        "id": "plumber",
        "title": "Plumber",
        "description": "Install and repair pipes that carry water, gas, and other fluids. Work on residential and commercial plumbing systems.",
        "industry": "Trades",
        "required_skills": ["plumbing_systems", "troubleshooting", "blueprint_reading", "physical_fitness", "customer_service"],
        "preferred_skills": ["pipefitting", "welding", "project_management", "green_plumbing"],
        "interests": ["trades", "hands_on_work", "problem_solving", "construction"],
        "education_level": "vocational",
        "experience_range": {"min": 0, "max": 30},
        "salary_range": {"min": 40000, "max": 95000},
        "salary_category": "medium",
        "growth_outlook": "Good",
        "work_styles": ["onsite"],
        "career_path": ["Apprentice", "Journeyman", "Master Plumber", "Plumbing Contractor", "Business Owner"]
    },
    {
        "id": "hvac_technician",
        "title": "HVAC Technician",
        "description": "Install and repair heating, ventilation, and air conditioning systems. Ensure climate control systems operate efficiently.",
        "industry": "Trades",
        "required_skills": ["hvac_systems", "troubleshooting", "mechanical_aptitude", "customer_service", "safety"],
        "preferred_skills": ["refrigeration", "electrical_knowledge", "energy_efficiency", "commercial_systems"],
        "interests": ["trades", "hands_on_work", "technology", "problem_solving"],
        "education_level": "vocational",
        "experience_range": {"min": 0, "max": 25},
        "salary_range": {"min": 40000, "max": 85000},
        "salary_category": "medium",
        "growth_outlook": "Good",
        "work_styles": ["onsite"],
        "career_path": ["Apprentice", "HVAC Technician", "Senior Technician", "HVAC Contractor", "Business Owner"]
    },
    
    # Public Service & Government
    {
        "id": "police_officer",
        "title": "Police Officer",
        "description": "Protect communities and enforce laws. Respond to emergencies, investigate crimes, and maintain public safety.",
        "industry": "Government",
        "required_skills": ["law_enforcement", "communication", "physical_fitness", "decision_making", "conflict_resolution"],
        "preferred_skills": ["investigation", "community_relations", "crisis_management", "first_aid"],
        "interests": ["public_service", "justice", "community", "protection"],
        "education_level": "associates",
        "experience_range": {"min": 0, "max": 30},
        "salary_range": {"min": 45000, "max": 100000},
        "salary_category": "medium",
        "growth_outlook": "Good",
        "work_styles": ["onsite"],
        "career_path": ["Patrol Officer", "Detective", "Sergeant", "Lieutenant", "Captain", "Chief of Police"]
    },
    {
        "id": "firefighter",
        "title": "Firefighter",
        "description": "Respond to fires and emergencies. Rescue people, extinguish fires, and provide emergency medical services.",
        "industry": "Government",
        "required_skills": ["firefighting", "physical_fitness", "teamwork", "emergency_response", "first_aid"],
        "preferred_skills": ["ems", "hazmat", "rescue", "fire_prevention"],
        "interests": ["public_service", "helping_others", "emergency_response", "physical_activity"],
        "education_level": "high_school",
        "experience_range": {"min": 0, "max": 30},
        "salary_range": {"min": 40000, "max": 90000},
        "salary_category": "medium",
        "growth_outlook": "Good",
        "work_styles": ["onsite"],
        "career_path": ["Firefighter", "Engineer", "Lieutenant", "Captain", "Battalion Chief", "Fire Chief"]
    },
    {
        "id": "social_worker",
        "title": "Social Worker",
        "description": "Help people cope with challenges. Provide counseling, resources, and support to individuals and families.",
        "industry": "Social Services",
        "required_skills": ["counseling", "empathy", "communication", "case_management", "crisis_intervention"],
        "preferred_skills": ["advocacy", "community_resources", "documentation", "cultural_competence"],
        "interests": ["helping_others", "social_justice", "community", "psychology"],
        "education_level": "masters",
        "experience_range": {"min": 0, "max": 30},
        "salary_range": {"min": 45000, "max": 85000},
        "salary_category": "medium",
        "growth_outlook": "Good",
        "work_styles": ["onsite", "hybrid"],
        "career_path": ["Case Worker", "Social Worker", "Senior Social Worker", "Clinical Social Worker", "Program Director"]
    },
    {
        "id": "urban_planner",
        "title": "Urban Planner",
        "description": "Develop land use plans and programs. Help create communities, accommodate population growth, and revitalize areas.",
        "industry": "Government",
        "required_skills": ["planning", "gis", "analysis", "communication", "project_management"],
        "preferred_skills": ["zoning", "policy_development", "public_engagement", "sustainability"],
        "interests": ["community", "design", "urban_development", "sustainability"],
        "education_level": "masters",
        "experience_range": {"min": 0, "max": 25},
        "salary_range": {"min": 55000, "max": 110000},
        "salary_category": "medium",
        "growth_outlook": "Good",
        "work_styles": ["hybrid", "onsite"],
        "career_path": ["Junior Planner", "Planner", "Senior Planner", "Planning Manager", "Planning Director"]
    },
    
    # Hospitality & Tourism
    {
        "id": "hotel_manager",
        "title": "Hotel Manager",
        "description": "Oversee daily operations of hotels or lodging facilities. Ensure guest satisfaction and manage staff.",
        "industry": "Hospitality",
        "required_skills": ["hospitality_management", "customer_service", "leadership", "operations_management", "communication"],
        "preferred_skills": ["revenue_management", "marketing", "multilingual", "conflict_resolution"],
        "interests": ["hospitality", "management", "customer_service", "travel"],
        "education_level": "bachelors",
        "experience_range": {"min": 3, "max": 25},
        "salary_range": {"min": 50000, "max": 120000},
        "salary_category": "medium",
        "growth_outlook": "Good",
        "work_styles": ["onsite"],
        "career_path": ["Assistant Manager", "Department Manager", "Hotel Manager", "General Manager", "Regional Director", "VP of Operations"]
    },
    {
        "id": "event_planner",
        "title": "Event Planner",
        "description": "Coordinate all aspects of events. Plan weddings, corporate events, conferences, and other special occasions.",
        "industry": "Events",
        "required_skills": ["event_planning", "organization", "communication", "negotiation", "creativity"],
        "preferred_skills": ["vendor_management", "budgeting", "marketing", "crisis_management"],
        "interests": ["events", "creativity", "organization", "people"],
        "education_level": "bachelors",
        "experience_range": {"min": 0, "max": 20},
        "salary_range": {"min": 40000, "max": 90000},
        "salary_category": "medium",
        "growth_outlook": "Good",
        "work_styles": ["hybrid", "onsite"],
        "career_path": ["Event Coordinator", "Event Planner", "Senior Planner", "Event Manager", "Director of Events"]
    },
    {
        "id": "chef",
        "title": "Chef",
        "description": "Prepare and cook meals in restaurants, hotels, and other establishments. Create menus and manage kitchen operations.",
        "industry": "Hospitality",
        "required_skills": ["culinary_skills", "creativity", "time_management", "leadership", "food_safety"],
        "preferred_skills": ["menu_development", "cost_control", "kitchen_management", "wine_pairing"],
        "interests": ["food", "creativity", "hospitality", "culinary_arts"],
        "education_level": "vocational",
        "experience_range": {"min": 0, "max": 30},
        "salary_range": {"min": 35000, "max": 100000},
        "salary_category": "medium",
        "growth_outlook": "Good",
        "work_styles": ["onsite"],
        "career_path": ["Line Cook", "Sous Chef", "Head Chef", "Executive Chef", "Restaurant Owner"]
    },
    
    # Sports & Fitness
    {
        "id": "personal_trainer",
        "title": "Personal Trainer",
        "description": "Help clients achieve fitness goals. Design workout programs, provide guidance, and motivate clients.",
        "industry": "Fitness",
        "required_skills": ["fitness_knowledge", "motivation", "communication", "program_design", "anatomy_knowledge"],
        "preferred_skills": ["nutrition", "injury_prevention", "specialized_training", "business_development"],
        "interests": ["fitness", "helping_others", "health", "sports"],
        "education_level": "certification",
        "experience_range": {"min": 0, "max": 25},
        "salary_range": {"min": 30000, "max": 75000},
        "salary_category": "medium",
        "growth_outlook": "Good",
        "work_styles": ["onsite", "hybrid"],
        "career_path": ["Personal Trainer", "Senior Trainer", "Fitness Manager", "Gym Director", "Fitness Business Owner"]
    },
    {
        "id": "sports_coach",
        "title": "Sports Coach",
        "description": "Train and mentor athletes. Develop strategies, conduct practices, and guide teams to success.",
        "industry": "Sports",
        "required_skills": ["sport_knowledge", "leadership", "communication", "strategy", "motivation"],
        "preferred_skills": ["player_development", "analytics", "recruiting", "media_relations"],
        "interests": ["sports", "competition", "teaching", "leadership"],
        "education_level": "bachelors",
        "experience_range": {"min": 0, "max": 35},
        "salary_range": {"min": 35000, "max": 150000},
        "salary_category": "medium",
        "growth_outlook": "Good",
        "work_styles": ["onsite"],
        "career_path": ["Assistant Coach", "Position Coach", "Coordinator", "Head Coach", "Athletic Director"]
    },
    
    # Transportation & Logistics
    {
        "id": "logistics_manager",
        "title": "Logistics Manager",
        "description": "Oversee supply chain operations. Coordinate transportation, warehousing, and distribution of goods.",
        "industry": "Logistics",
        "required_skills": ["supply_chain_management", "logistics", "problem_solving", "communication", "organization"],
        "preferred_skills": ["warehouse_management", "transportation", "inventory_control", "erp_systems"],
        "interests": ["logistics", "organization", "operations", "efficiency"],
        "education_level": "bachelors",
        "experience_range": {"min": 3, "max": 25},
        "salary_range": {"min": 60000, "max": 130000},
        "salary_category": "high",
        "growth_outlook": "Good",
        "work_styles": ["onsite", "hybrid"],
        "career_path": ["Logistics Coordinator", "Logistics Analyst", "Logistics Manager", "Director of Logistics", "VP of Supply Chain"]
    },
    {
        "id": "airline_pilot",
        "title": "Airline Pilot",
        "description": "Fly and navigate aircraft. Transport passengers and cargo safely to destinations.",
        "industry": "Aviation",
        "required_skills": ["aviation", "decision_making", "communication", "navigation", "physical_fitness"],
        "preferred_skills": ["leadership", "crisis_management", "meteorology", "technical_systems"],
        "interests": ["aviation", "travel", "technology", "adventure"],
        "education_level": "bachelors",
        "experience_range": {"min": 0, "max": 40},
        "salary_range": {"min": 80000, "max": 250000},
        "salary_category": "high",
        "growth_outlook": "Good",
        "work_styles": ["onsite"],
        "career_path": ["First Officer", "Captain", "Check Pilot", "Chief Pilot"]
    },
    
    # Real Estate
    {
        "id": "real_estate_agent",
        "title": "Real Estate Agent",
        "description": "Help clients buy, sell, or rent properties. Provide market knowledge, negotiate deals, and guide transactions.",
        "industry": "Real Estate",
        "required_skills": ["sales", "negotiation", "communication", "market_knowledge", "networking"],
        "preferred_skills": ["marketing", "property_valuation", "client_management", "social_media"],
        "interests": ["real_estate", "sales", "people", "entrepreneurship"],
        "education_level": "high_school",
        "experience_range": {"min": 0, "max": 30},
        "salary_range": {"min": 30000, "max": 150000},
        "salary_category": "medium",
        "growth_outlook": "Good",
        "work_styles": ["hybrid"],
        "career_path": ["Real Estate Agent", "Senior Agent", "Team Leader", "Broker", "Brokerage Owner"]
    },
    {
        "id": "property_manager",
        "title": "Property Manager",
        "description": "Manage residential or commercial properties. Handle tenant relations, maintenance, and financial operations.",
        "industry": "Real Estate",
        "required_skills": ["property_management", "customer_service", "budgeting", "maintenance_coordination", "communication"],
        "preferred_skills": ["leasing", "legal_knowledge", "vendor_management", "software_systems"],
        "interests": ["real_estate", "management", "organization", "problem_solving"],
        "education_level": "bachelors",
        "experience_range": {"min": 1, "max": 25},
        "salary_range": {"min": 45000, "max": 95000},
        "salary_category": "medium",
        "growth_outlook": "Good",
        "work_styles": ["onsite", "hybrid"],
        "career_path": ["Assistant Manager", "Property Manager", "Regional Manager", "Director of Property Management", "VP of Real Estate"]
    },
    
    # Agriculture
    {
        "id": "agricultural_scientist",
        "title": "Agricultural Scientist",
        "description": "Research ways to improve farming practices. Study crop yields, soil health, and sustainable agriculture methods.",
        "industry": "Agriculture",
        "required_skills": ["agricultural_science", "research", "data_analysis", "problem_solving", "fieldwork"],
        "preferred_skills": ["biotechnology", "soil_science", "sustainability", "grant_writing"],
        "interests": ["agriculture", "science", "sustainability", "nature"],
        "education_level": "masters",
        "experience_range": {"min": 0, "max": 25},
        "salary_range": {"min": 55000, "max": 100000},
        "salary_category": "medium",
        "growth_outlook": "Good",
        "work_styles": ["hybrid", "onsite"],
        "career_path": ["Research Assistant", "Agricultural Scientist", "Senior Scientist", "Research Director"]
    },
    {
        "id": "farm_manager",
        "title": "Farm Manager",
        "description": "Oversee farm operations. Manage crops, livestock, staff, and budgets to ensure profitability.",
        "industry": "Agriculture",
        "required_skills": ["farm_management", "agriculture_knowledge", "budgeting", "leadership", "problem_solving"],
        "preferred_skills": ["equipment_operation", "sustainability", "marketing", "business_management"],
        "interests": ["agriculture", "outdoors", "management", "nature"],
        "education_level": "bachelors",
        "experience_range": {"min": 2, "max": 30},
        "salary_range": {"min": 45000, "max": 90000},
        "salary_category": "medium",
        "growth_outlook": "Fair",
        "work_styles": ["onsite"],
        "career_path": ["Assistant Manager", "Farm Manager", "Operations Director", "Farm Owner"]
    },
    
    # Non-Profit & NGO
    {
        "id": "nonprofit_director",
        "title": "Non-Profit Director",
        "description": "Lead non-profit organizations. Oversee programs, fundraising, staff, and strategic direction.",
        "industry": "Non-Profit",
        "required_skills": ["leadership", "fundraising", "strategic_planning", "communication", "program_management"],
        "preferred_skills": ["grant_writing", "board_management", "advocacy", "financial_management"],
        "interests": ["social_impact", "helping_others", "leadership", "community"],
        "education_level": "masters",
        "experience_range": {"min": 5, "max": 30},
        "salary_range": {"min": 60000, "max": 150000},
        "salary_category": "medium",
        "growth_outlook": "Good",
        "work_styles": ["hybrid", "onsite"],
        "career_path": ["Program Manager", "Director of Programs", "Executive Director", "CEO"]
    },
    {
        "id": "fundraiser",
        "title": "Fundraiser/Development Officer",
        "description": "Raise money for organizations. Plan campaigns, cultivate donors, and manage fundraising events.",
        "industry": "Non-Profit",
        "required_skills": ["fundraising", "communication", "relationship_building", "event_planning", "writing"],
        "preferred_skills": ["major_gifts", "grant_writing", "crm_systems", "marketing"],
        "interests": ["social_impact", "communication", "helping_others", "relationship_building"],
        "education_level": "bachelors",
        "experience_range": {"min": 0, "max": 25},
        "salary_range": {"min": 40000, "max": 100000},
        "salary_category": "medium",
        "growth_outlook": "Good",
        "work_styles": ["hybrid", "onsite"],
        "career_path": ["Development Coordinator", "Development Officer", "Major Gifts Officer", "Director of Development", "Chief Development Officer"]
    },
    
    # Arts & Entertainment
    {
        "id": "musician",
        "title": "Professional Musician",
        "description": "Perform music as a career. Play instruments, sing, compose, or produce music for various audiences.",
        "industry": "Entertainment",
        "required_skills": ["musical_talent", "performance", "creativity", "practice", "collaboration"],
        "preferred_skills": ["music_theory", "recording", "songwriting", "networking"],
        "interests": ["music", "creativity", "performance", "entertainment"],
        "education_level": "bachelors",
        "experience_range": {"min": 0, "max": 40},
        "salary_range": {"min": 25000, "max": 200000},
        "salary_category": "medium",
        "growth_outlook": "Fair",
        "work_styles": ["hybrid", "onsite"],
        "career_path": ["Session Musician", "Performer", "Band Member", "Solo Artist", "Music Director"]
    },
    {
        "id": "actor",
        "title": "Actor",
        "description": "Perform in theatrical productions, films, television, or other media. Bring characters to life through performance.",
        "industry": "Entertainment",
        "required_skills": ["acting", "memorization", "emotional_intelligence", "collaboration", "resilience"],
        "preferred_skills": ["singing", "dancing", "accents", "stunt_work"],
        "interests": ["performing", "creativity", "storytelling", "entertainment"],
        "education_level": "bachelors",
        "experience_range": {"min": 0, "max": 50},
        "salary_range": {"min": 20000, "max": 500000},
        "salary_category": "medium",
        "growth_outlook": "Fair",
        "work_styles": ["onsite"],
        "career_path": ["Extra", "Supporting Actor", "Lead Actor", "Star"]
    },
    
    # Insurance
    {
        "id": "actuary",
        "title": "Actuary",
        "description": "Analyze financial costs of risk and uncertainty. Use mathematics and statistics to assess insurance risks.",
        "industry": "Insurance",
        "required_skills": ["mathematics", "statistics", "data_analysis", "problem_solving", "communication"],
        "preferred_skills": ["programming", "financial_modeling", "insurance_knowledge", "business_acumen"],
        "interests": ["mathematics", "finance", "analysis", "risk"],
        "education_level": "bachelors",
        "experience_range": {"min": 0, "max": 30},
        "salary_range": {"min": 70000, "max": 180000},
        "salary_category": "high",
        "growth_outlook": "Excellent",
        "work_styles": ["hybrid", "remote"],
        "career_path": ["Actuarial Analyst", "Associate Actuary", "Senior Actuary", "Chief Actuary"]
    },
    {
        "id": "insurance_underwriter",
        "title": "Insurance Underwriter",
        "description": "Evaluate insurance applications and determine risk. Decide coverage terms and premium rates.",
        "industry": "Insurance",
        "required_skills": ["risk_assessment", "analysis", "decision_making", "attention_to_detail", "communication"],
        "preferred_skills": ["insurance_products", "data_analysis", "negotiation", "industry_knowledge"],
        "interests": ["analysis", "risk", "finance", "decision_making"],
        "education_level": "bachelors",
        "experience_range": {"min": 0, "max": 25},
        "salary_range": {"min": 50000, "max": 110000},
        "salary_category": "medium",
        "growth_outlook": "Good",
        "work_styles": ["hybrid", "onsite"],
        "career_path": ["Junior Underwriter", "Underwriter", "Senior Underwriter", "Underwriting Manager", "Chief Underwriting Officer"]
    },
    
    # Retail & E-commerce
    {
        "id": "retail_manager",
        "title": "Retail Manager",
        "description": "Manage retail store operations. Oversee staff, inventory, sales, and customer service.",
        "industry": "Retail",
        "required_skills": ["retail_management", "customer_service", "leadership", "sales", "inventory_management"],
        "preferred_skills": ["merchandising", "training", "loss_prevention", "analytics"],
        "interests": ["retail", "management", "customer_service", "business"],
        "education_level": "associates",
        "experience_range": {"min": 1, "max": 25},
        "salary_range": {"min": 35000, "max": 80000},
        "salary_category": "medium",
        "growth_outlook": "Fair",
        "work_styles": ["onsite"],
        "career_path": ["Assistant Manager", "Store Manager", "District Manager", "Regional Manager", "VP of Retail"]
    },
    {
        "id": "ecommerce_manager",
        "title": "E-commerce Manager",
        "description": "Manage online retail operations. Oversee website, digital marketing, and online customer experience.",
        "industry": "E-commerce",
        "required_skills": ["digital_marketing", "e_commerce_platforms", "analytics", "project_management", "customer_experience"],
        "preferred_skills": ["seo", "ppc", "conversion_optimization", "inventory_management"],
        "interests": ["technology", "retail", "digital_marketing", "business"],
        "education_level": "bachelors",
        "experience_range": {"min": 2, "max": 20},
        "salary_range": {"min": 60000, "max": 130000},
        "salary_category": "high",
        "growth_outlook": "Excellent",
        "work_styles": ["remote", "hybrid"],
        "career_path": ["E-commerce Coordinator", "E-commerce Manager", "Director of E-commerce", "VP of Digital Commerce", "Chief Digital Officer"]
    },
    
    # Psychology & Mental Health
    {
        "id": "psychologist",
        "title": "Psychologist",
        "description": "Study mental processes and human behavior. Diagnose and treat mental health conditions through therapy.",
        "industry": "Healthcare",
        "required_skills": ["psychology", "counseling", "empathy", "communication", "assessment"],
        "preferred_skills": ["research", "specialized_therapy", "testing", "cultural_competence"],
        "interests": ["psychology", "helping_others", "mental_health", "research"],
        "education_level": "doctorate",
        "experience_range": {"min": 0, "max": 35},
        "salary_range": {"min": 70000, "max": 150000},
        "salary_category": "high",
        "growth_outlook": "Good",
        "work_styles": ["hybrid", "onsite"],
        "career_path": ["Psychologist", "Senior Psychologist", "Clinical Director", "Private Practice Owner"]
    },
    {
        "id": "counselor",
        "title": "Mental Health Counselor",
        "description": "Provide counseling to individuals and groups. Help clients with mental health issues, addiction, and life challenges.",
        "industry": "Healthcare",
        "required_skills": ["counseling", "empathy", "communication", "active_listening", "crisis_intervention"],
        "preferred_skills": ["specialized_therapy", "group_facilitation", "assessment", "cultural_competence"],
        "interests": ["helping_others", "mental_health", "psychology", "counseling"],
        "education_level": "masters",
        "experience_range": {"min": 0, "max": 30},
        "salary_range": {"min": 45000, "max": 85000},
        "salary_category": "medium",
        "growth_outlook": "Very Good",
        "work_styles": ["hybrid", "onsite"],
        "career_path": ["Counselor", "Senior Counselor", "Clinical Supervisor", "Practice Director"]
    },
    
    # Media & Journalism
    {
        "id": "journalist",
        "title": "Journalist",
        "description": "Research and report news stories. Investigate topics, conduct interviews, and write articles for publication.",
        "industry": "Media",
        "required_skills": ["writing", "research", "interviewing", "critical_thinking", "deadline_management"],
        "preferred_skills": ["multimedia", "social_media", "data_journalism", "investigative_skills"],
        "interests": ["writing", "news", "investigation", "storytelling"],
        "education_level": "bachelors",
        "experience_range": {"min": 0, "max": 30},
        "salary_range": {"min": 35000, "max": 100000},
        "salary_category": "medium",
        "growth_outlook": "Fair",
        "work_styles": ["hybrid", "remote"],
        "career_path": ["Reporter", "Senior Reporter", "Editor", "Senior Editor", "Editor-in-Chief"]
    },
    {
        "id": "public_relations_specialist",
        "title": "Public Relations Specialist",
        "description": "Manage public image for organizations. Create press releases, plan events, and handle media relations.",
        "industry": "Communications",
        "required_skills": ["communication", "writing", "media_relations", "crisis_management", "creativity"],
        "preferred_skills": ["social_media", "event_planning", "strategic_planning", "networking"],
        "interests": ["communication", "media", "relationship_building", "creativity"],
        "education_level": "bachelors",
        "experience_range": {"min": 0, "max": 25},
        "salary_range": {"min": 45000, "max": 120000},
        "salary_category": "medium",
        "growth_outlook": "Good",
        "work_styles": ["hybrid", "onsite"],
        "career_path": ["PR Coordinator", "PR Specialist", "PR Manager", "Director of PR", "VP of Communications", "Chief Communications Officer"]
    },
    
    # Construction
    {
        "id": "construction_manager",
        "title": "Construction Manager",
        "description": "Plan, coordinate, and supervise construction projects. Manage budgets, timelines, and construction teams.",
        "industry": "Construction",
        "required_skills": ["construction_management", "project_management", "budgeting", "leadership", "problem_solving"],
        "preferred_skills": ["scheduling_software", "building_codes", "safety", "negotiation"],
        "interests": ["construction", "management", "building", "leadership"],
        "education_level": "bachelors",
        "experience_range": {"min": 3, "max": 30},
        "salary_range": {"min": 70000, "max": 150000},
        "salary_category": "high",
        "growth_outlook": "Good",
        "work_styles": ["onsite"],
        "career_path": ["Assistant PM", "Project Manager", "Senior PM", "Construction Manager", "Director of Construction", "VP of Construction"]
    },
    {
        "id": "civil_engineer",
        "title": "Civil Engineer",
        "description": "Design, build, and supervise infrastructure projects. Work on roads, bridges, buildings, and water systems.",
        "industry": "Engineering",
        "required_skills": ["civil_engineering", "cad_software", "project_management", "problem_solving", "technical_writing"],
        "preferred_skills": ["structural_analysis", "sustainability", "construction_management", "bim"],
        "interests": ["engineering", "construction", "design", "infrastructure"],
        "education_level": "bachelors",
        "experience_range": {"min": 0, "max": 30},
        "salary_range": {"min": 65000, "max": 140000},
        "salary_category": "high",
        "growth_outlook": "Good",
        "work_styles": ["hybrid", "onsite"],
        "career_path": ["Junior Engineer", "Civil Engineer", "Senior Engineer", "Project Manager", "Principal Engineer", "Director of Engineering"]
    },
    
    # Telecommunications
    {
        "id": "network_engineer",
        "title": "Network Engineer",
        "description": "Design and implement computer networks. Manage network infrastructure, security, and performance.",
        "industry": "Technology",
        "required_skills": ["networking", "troubleshooting", "network_security", "infrastructure", "documentation"],
        "preferred_skills": ["cloud_networking", "automation", "wireless", "voip"],
        "interests": ["technology", "networking", "problem_solving", "infrastructure"],
        "education_level": "bachelors",
        "experience_range": {"min": 0, "max": 20},
        "salary_range": {"min": 65000, "max": 140000},
        "salary_category": "high",
        "growth_outlook": "Good",
        "work_styles": ["hybrid", "onsite"],
        "career_path": ["Junior Network Engineer", "Network Engineer", "Senior Network Engineer", "Network Architect", "Director of Network Infrastructure"]
    },
    
    # Energy
    {
        "id": "renewable_energy_engineer",
        "title": "Renewable Energy Engineer",
        "description": "Design and develop renewable energy systems. Work on solar, wind, and other sustainable energy technologies.",
        "industry": "Energy",
        "required_skills": ["engineering", "renewable_energy", "problem_solving", "project_management", "technical_design"],
        "preferred_skills": ["solar_design", "wind_technology", "energy_storage", "grid_integration"],
        "interests": ["sustainability", "engineering", "environment", "innovation"],
        "education_level": "bachelors",
        "experience_range": {"min": 0, "max": 25},
        "salary_range": {"min": 70000, "max": 130000},
        "salary_category": "high",
        "growth_outlook": "Excellent",
        "work_styles": ["hybrid", "onsite"],
        "career_path": ["Junior Engineer", "Renewable Energy Engineer", "Senior Engineer", "Project Manager", "Director of Renewable Energy"]
    },
    {
        "id": "petroleum_engineer",
        "title": "Petroleum Engineer",
        "description": "Design methods for extracting oil and gas. Optimize production and develop drilling techniques.",
        "industry": "Energy",
        "required_skills": ["petroleum_engineering", "problem_solving", "technical_analysis", "project_management", "geology_knowledge"],
        "preferred_skills": ["drilling_technology", "reservoir_engineering", "simulation", "field_operations"],
        "interests": ["engineering", "energy", "problem_solving", "geology"],
        "education_level": "bachelors",
        "experience_range": {"min": 0, "max": 30},
        "salary_range": {"min": 80000, "max": 180000},
        "salary_category": "high",
        "growth_outlook": "Fair",
        "work_styles": ["onsite", "hybrid"],
        "career_path": ["Junior Engineer", "Petroleum Engineer", "Senior Engineer", "Drilling Manager", "VP of Operations"]
    }
]

# Skills master list with categories
SKILLS_DATABASE = {
    "technical": [
        "programming", "python", "javascript", "html_css", "sql", "data_analysis",
        "machine_learning", "deep_learning", "cloud_computing", "databases",
        "api_development", "mobile_development", "web_design", "cybersecurity",
        "networking", "devops", "automation", "testing", "algorithms", "software_design",
        "react", "nodejs", "linux", "docker", "kubernetes", "aws", "azure", "gcp",
        "tensorflow", "pytorch", "nlp", "computer_vision", "big_data", "visualization",
        "version_control", "ci_cd", "scripting", "ethical_hacking", "incident_response"
    ],
    "business": [
        "project_management", "strategic_planning", "budgeting", "financial_analysis",
        "marketing_strategy", "sales", "negotiation", "business_development",
        "product_strategy", "accounting", "financial_modeling", "valuation",
        "consulting", "operations_management", "supply_chain_management", "logistics"
    ],
    "communication": [
        "writing", "presentation", "public_speaking", "communication", "storytelling",
        "interviewing", "media_relations", "content_strategy", "copywriting"
    ],
    "leadership": [
        "leadership", "team_management", "mentoring", "decision_making", "coaching",
        "conflict_resolution", "change_management", "stakeholder_management"
    ],
    "creative": [
        "creativity", "design_thinking", "visual_design", "ui_design", "graphic_design",
        "illustration", "animation", "video_editing", "photography", "branding",
        "typography", "color_theory", "adobe_creative_suite", "figma", "prototyping"
    ],
    "analytical": [
        "research", "critical_thinking", "problem_solving", "data_analysis", "statistics",
        "analytical_skills", "attention_to_detail", "risk_assessment", "auditing"
    ],
    "healthcare": [
        "patient_care", "medical_knowledge", "diagnosis", "treatment_planning",
        "pharmaceutical_knowledge", "anatomy_knowledge", "laboratory_skills",
        "clinical_skills", "healthcare_knowledge"
    ],
    "interpersonal": [
        "empathy", "teamwork", "customer_service", "relationship_building",
        "networking", "collaboration", "cultural_competence", "active_listening"
    ]
}

# Interests master list
INTERESTS_DATABASE = [
    "technology", "programming", "coding", "innovation", "artificial_intelligence",
    "data", "research", "science", "mathematics", "discovery",
    "design", "creativity", "art", "visual_communication", "animation",
    "writing", "storytelling", "journalism", "communication",
    "business", "finance", "economics", "entrepreneurship", "strategy",
    "healthcare", "medicine", "helping_others", "caregiving", "mental_health",
    "education", "teaching", "learning", "academia", "youth",
    "law", "justice", "advocacy", "ethics",
    "environment", "sustainability", "nature", "conservation",
    "sports", "fitness", "health", "competition", "physical_activity",
    "music", "performing", "entertainment", "theater",
    "travel", "hospitality", "food", "culinary_arts",
    "construction", "building", "architecture", "infrastructure",
    "public_service", "community", "social_impact", "social_justice",
    "organization", "detail_oriented", "problem_solving", "analysis",
    "leadership", "management", "people", "teamwork",
    "sales", "marketing", "relationship_building",
    "hands_on_work", "trades", "mechanical", "outdoors"
]

# Industries master list
INDUSTRIES_DATABASE = [
    "Technology", "Healthcare", "Finance", "Consulting", "Marketing",
    "Human Resources", "Design", "Media", "Entertainment", "Education",
    "Legal", "Science", "Environmental", "Biotechnology", "Trades",
    "Government", "Social Services", "Hospitality", "Events", "Fitness",
    "Sports", "Logistics", "Aviation", "Real Estate", "Agriculture",
    "Non-Profit", "Insurance", "Retail", "E-commerce", "Communications",
    "Construction", "Engineering", "Energy", "Multiple"
]

# Education levels
EDUCATION_LEVELS = {
    "high_school": 1,
    "vocational": 2,
    "certification": 2,
    "associates": 3,
    "bachelors": 4,
    "masters": 5,
    "doctorate": 6
}
